/* eslint-disable */
module.exports = [
  {"content":[{"insert":"W"}],"id":"f2VOQIqn","level":0,"type":"title","before":null,"after":"tzt7XTD6"},
  {"content":[{"insert":"Events"}],"id":"tzt7XTD6","level":1,"type":"bullet","before":"f2VOQIqn","after":"GAO4DKMc"},
  {"content":[{"insert":"Software Estimation Workshop"}],"id":"GAO4DKMc","level":2,"type":"bullet","before":"tzt7XTD6","after":"mUBkuTo3"},
  {"content":[{"insert":"const foo = () = 'bar';"}],"id":"mUBkuTo3","level":3,"type":"code","before":"GAO4DKMc","after":"4wlBFFLJ"},
  {"content":[{"insert":`Lorem ipsum dolor sit amet,\n\n\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`}],"type":"paragraph","id":"4wlBFFLJ","level":3,"before":"mUBkuTo3","after":"CiDKl4fU"},
  {"content":[{"insert":"Third: TDD, verify"}],"id":"CiDKl4fU","level":3,"type":"bullet","before":"4wlBFFLJ","after":"TztbCYnR"},
  {"content":[{"insert":"Verify"}],"id":"TztbCYnR","level":4,"type":"bullet","before":"CiDKl4fU","after":"_JE4eCYJ"},
  {"content":[{"insert":"Average fix time"}],"id":"_JE4eCYJ","level":4,"type":"bullet","before":"TztbCYnR","after":"hY2ZfFbn"},
  {"content":[{"insert":"Design review"}],"id":"hY2ZfFbn","level":5,"type":"bullet","before":"_JE4eCYJ","after":"OaKVXhzR"},
  {"content":[{"insert":"``Code"}],"id":"OaKVXhzR","level":5,"type":"bullet","before":"hY2ZfFbn","after":"yD0WuY_i"},
  {"content":[{"insert":"Code review"}],"id":"yD0WuY_i","level":5,"type":"bullet","before":"OaKVXhzR","after":"w3z07Z5M"},
  {"content":[{"insert":"Compile"}],"id":"w3z07Z5M","level":5,"type":"bullet","before":"yD0WuY_i","after":"Ol5EFuV0"},
  {"content":[{"insert":"Test"}],"id":"Ol5EFuV0","level":5,"type":"bullet","before":"w3z07Z5M","after":"3wvM5iNk"},
  {"content":[{"insert":"Use"}],"id":"3wvM5iNk","level":5,"type":"bullet","before":"Ol5EFuV0","after":"5O1O9Xtm"},
  {"content":[{"insert":"Project quality statistic"}],"id":"5O1O9Xtm","level":4,"type":"bullet","before":"3wvM5iNk","after":"Hy_eRWmk"},
  {"content":[{"insert":"Test"}],"id":"Hy_eRWmk","level":4,"type":"bullet","before":"5O1O9Xtm","after":"IPtSFhFH"},
  {"content":[{"insert":"Unit test"}],"id":"IPtSFhFH","level":5,"type":"bullet","before":"Hy_eRWmk","after":"-7-1E-Ln"},
  {"content":[{"insert":"Integration test"}],"id":"-7-1E-Ln","level":5,"type":"bullet","before":"IPtSFhFH","after":"3HOtx_yp"},
  {"content":[{"insert":"Functional test"}],"id":"3HOtx_yp","level":5,"type":"bullet","before":"-7-1E-Ln","after":"IidP_CcK"},
  {"content":[{"insert":"Smoke test"}],"id":"IidP_CcK","level":5,"type":"bullet","before":"3HOtx_yp","after":"NZHSiM_P"},
  {"content":[{"insert":"Regression test"}],"id":"NZHSiM_P","level":5,"type":"bullet","before":"IidP_CcK","after":"Zph7qhgn"},
  {"content":[{"insert":"Acceptance test"}],"id":"Zph7qhgn","level":5,"type":"bullet","before":"NZHSiM_P","after":"A3DWUoVL"},
  {"content":[{"insert":"QA"}],"id":"A3DWUoVL","level":4,"type":"bullet","before":"Zph7qhgn","after":"ZtL0Yv5w"},
  {"content":[{"insert":"Test plan"}],"id":"ZtL0Yv5w","level":5,"type":"bullet","before":"A3DWUoVL","after":"u3BrZvGB"},
  {"content":[{"insert":"Test case"}],"id":"u3BrZvGB","level":4,"type":"bullet","before":"ZtL0Yv5w","after":"SgYsaxoB"},
  {"content":[{"insert":"Notes"}],"id":"SgYsaxoB","level":4,"type":"bullet","before":"u3BrZvGB","after":"wEnS4bym"},
  {"content":[{"insert":"Viết unit test sẽ tiết kiệm thời gian"}],"id":"wEnS4bym","level":5,"type":"bullet","before":"SgYsaxoB","after":"p6wAChQp"},
  {"content":[{"insert":"Thời gian để đưa sang team tester -&gt; report -&gt; fix -&gt; regression test gấp 3 lần thời gian"}],"id":"p6wAChQp","level":5,"type":"bullet","before":"wEnS4bym","after":"6hVAPNm7"},
  {"content":[{"insert":"Test fail được đưa vào regression test, được kiểm tra lại mỗi khi có feature mới"}],"id":"6hVAPNm7","level":5,"type":"bullet","before":"p6wAChQp","after":"1bcCw3yt"},
  {"content":[{"insert":"Unit tests"}],"id":"1bcCw3yt","level":4,"type":"bullet","before":"6hVAPNm7","after":"B3kFZyKZ"},
  {"content":[{"insert":"Naming convention"}],"id":"B3kFZyKZ","level":5,"type":"bullet","before":"1bcCw3yt","after":"Is7rN-eB"},
  {"content":[{"insert":"FOO#123.2 Invalid email"}],"id":"Is7rN-eB","level":6,"type":"bullet","before":"B3kFZyKZ","after":"pbqoeN2Y"},
  {"content":[{"insert":"Description (step to reproduce)"}],"id":"pbqoeN2Y","level":5,"type":"bullet","before":"Is7rN-eB","after":"2oWFlyw6"},
  {"content":[{"insert":"Prepare 'test environment'"}],"id":"2oWFlyw6","level":5,"type":"bullet","before":"pbqoeN2Y","after":"GhHA75pM"},
  {"content":[{"insert":"Verification step"}],"id":"GhHA75pM","level":5,"type":"bullet","before":"2oWFlyw6","after":"E7qfG8Iz"},
  {"content":[{"insert":"Clear environment after finish"}],"id":"E7qfG8Iz","level":5,"type":"bullet","before":"GhHA75pM","after":"6rZo_WEB"},
  {"content":[{"insert":"Exercise"}],"id":"6rZo_WEB","level":4,"type":"bullet","before":"E7qfG8Iz","after":"460N4Hl3"},
  {"content":[{"insert":"Testable code"}],"id":"460N4Hl3","level":4,"type":"bullet","before":"6rZo_WEB","after":"AiwRpEMD"},
  {"content":[{"insert":"Design for startup"}],"id":"AiwRpEMD","level":2,"type":"bullet","before":"460N4Hl3","after":"eMT-bhzr"},
  {"content":[{"insert":"Hubba"}],"id":"eMT-bhzr","level":3,"type":"bullet","before":"AiwRpEMD","after":"mjwvizGi"},
  {"content":[{"insert":"Event community, connect people and friends in local events"}],"id":"mjwvizGi","level":4,"type":"bullet","before":"eMT-bhzr","after":"NtLVYjlg"},
  {"content":[{"insert":"Crew Fire (first)"}],"id":"NtLVYjlg","level":3,"type":"bullet","before":"mjwvizGi","after":"dLG7XYLZ"},
  {"content":[{"insert":"Marketing amplified"}],"id":"dLG7XYLZ","level":4,"type":"bullet","before":"NtLVYjlg","after":"kpNIClng"},
  {"content":[{"insert":"Meme App (second)"}],"id":"kpNIClng","level":3,"type":"bullet","before":"dLG7XYLZ","after":"f3eSPAzH"},
  {"content":[{"insert":"Uber for ecommerce, like ChoTot"}],"id":"f3eSPAzH","level":4,"type":"bullet","before":"kpNIClng","after":"uWO1Kl6t"},
  {"content":[{"insert":"Triip.me"}],"id":"uWO1Kl6t","level":3,"type":"bullet","before":"f3eSPAzH","after":"dmwC36kS"},
  {"content":[{"insert":"Uber for travelers"}],"id":"dmwC36kS","level":4,"type":"bullet","before":"uWO1Kl6t","after":"izq1yuBK"},
  {"content":[{"insert":"Q"}],"id":"izq1yuBK","level":4,"type":"bullet","before":"dmwC36kS","after":"PRMaY3m0"},
  {"content":[{"insert":"Làm sao người dùng biết được thương hiệu triip.me"}],"id":"PRMaY3m0","level":5,"type":"bullet","before":"izq1yuBK","after":"7BvSUTln"},
  {"content":[{"insert":"Umbala"}],"id":"7BvSUTln","level":3,"type":"bullet","before":"PRMaY3m0","after":"aSM5nNK4"},
  {"content":[{"insert":"Mobile video platform, helps young people produce, distribute and explore unique video with mind-blowing effects"}],"id":"aSM5nNK4","level":4,"type":"bullet","before":"7BvSUTln","after":"RIT2uJdT"},
  {"content":[{"insert":"Q"}],"id":"RIT2uJdT","level":4,"type":"bullet","before":"aSM5nNK4","after":"ymjT54PZ"},
  {"content":[{"insert":"No platform convention, cartoonist"}],"id":"ymjT54PZ","level":5,"type":"bullet","before":"RIT2uJdT","after":"kXI8F0qN"},
  {"content":[{"insert":"Brand color"}],"id":"kXI8F0qN","level":5,"type":"bullet","before":"ymjT54PZ","after":"uOcg60Jm"},
  {"content":[{"insert":"No brand personality"}],"id":"uOcg60Jm","level":5,"type":"bullet","before":"kXI8F0qN","after":"DvNomoPP"},
  {"content":[{"insert":"Visual direction no good"}],"id":"DvNomoPP","level":5,"type":"bullet","before":"uOcg60Jm","after":"7rboUjrq"},
  {"content":[{"insert":"Teach Me"}],"id":"7rboUjrq","level":3,"type":"bullet","before":"DvNomoPP","after":"oIVbGEED"},
  {"content":[{"insert":"Mobile app help connect learning and teaching at teal-time and real-location."}],"id":"oIVbGEED","level":4,"type":"bullet","before":"7rboUjrq","after":"Pbmdf0XI"},
  {"content":[{"insert":"Uber for tutor"}],"id":"Pbmdf0XI","level":4,"type":"bullet","before":"oIVbGEED","after":"Q02RyDmr"},
  {"content":[{"insert":"Q"}],"id":"Q02RyDmr","level":4,"type":"bullet","before":"Pbmdf0XI","after":"U0t2yxJe"},
  {"content":[{"insert":"Quá ít thông tin trên card"}],"id":"U0t2yxJe","level":5,"type":"bullet","before":"Q02RyDmr","after":"2-iD6Fbf"},
  {"content":[{"insert":"Cart Quickly"}],"id":"2-iD6Fbf","level":3,"type":"bullet","before":"U0t2yxJe","after":"GyBl1Snb"},
  {"content":[{"insert":"New grocery &amp; food shopping experience"}],"id":"GyBl1Snb","level":4,"type":"bullet","before":"2-iD6Fbf","after":"gGetSRqg"},
  {"content":[{"insert":"A platform to bring real-life shopping experience to online so that everyone can shop more conveniently and enjoy life better."}],"id":"gGetSRqg","level":4,"type":"bullet","before":"GyBl1Snb","after":"bOBRdblR"},
  {"content":[{"insert":"Q"}],"id":"bOBRdblR","level":4,"type":"bullet","before":"gGetSRqg","after":"NQraMtV8"},
  {"content":[{"insert":"New design for men more than women (?)"}],"id":"NQraMtV8","level":5,"type":"bullet","before":"bOBRdblR","after":"4HrIuK_7"},
  {"content":[{"insert":"70% women"}],"id":"4HrIuK_7","level":6,"type":"bullet","before":"NQraMtV8","after":"1bcraM8Y"},
  {"content":[{"insert":"30% men"}],"id":"1bcraM8Y","level":6,"type":"bullet","before":"4HrIuK_7","after":"XAYcBAO8"},
  {"content":[{"insert":"Need to test on users"}],"id":"XAYcBAO8","level":6,"type":"bullet","before":"1bcraM8Y","after":"_kvOjU2t"},
  {"content":[{"insert":"Nghiên cứu đối thủ cạnh tranh"}],"id":"_kvOjU2t","level":1,"type":"bullet","before":"XAYcBAO8","after":"uStUI7e_"},
  {"content":[{"insert":"Transpose:https://transpose.com/"}],"id":"uStUI7e_","level":2,"type":"bullet","before":"_kvOjU2t","after":"bJSgPlcJ"},
  {"content":[{"insert":"Search channel"}],"id":"bJSgPlcJ","level":3,"type":"bullet","before":"uStUI7e_","after":"hQ1eiwkf"},
  {"content":[{"insert":"Quora: follow"}],"id":"hQ1eiwkf","level":4,"type":"bullet","before":"bJSgPlcJ","after":"r77VLkoE"},
  {"content":[{"insert":"Medium:"}],"id":"r77VLkoE","level":4,"type":"bullet","before":"hQ1eiwkf","after":"p0WkimgA"},
  {"content":[{"insert":"https://medium.com/@transpose/here-s-how-we-went-from-0-to-100-000-users-with-0-in-marketing-2db04228ade0#.vnamkpqk2"}],"id":"p0WkimgA","level":5,"type":"bullet","before":"r77VLkoE","after":"z_XyHoi6"},
  {"content":[{"insert":"Time:  6 months: 100,000 users"}],"id":"z_XyHoi6","level":5,"type":"bullet","before":"p0WkimgA","after":"8vUpy4Ki"},
  {"content":[{"insert":"Tactics: "}],"id":"8vUpy4Ki","level":5,"type":"bullet","before":"z_XyHoi6","after":"ehlrkzlO"},
  {"content":[{"insert":"Social Media: "}],"id":"ehlrkzlO","level":6,"type":"bullet","before":"8vUpy4Ki","after":"T_Guz34Z"},
  {"content":[{"insert":"Twitter: searches on Twitter for topics that might lead them to users like 'note', 'online form'"}],"id":"T_Guz34Z","level":7,"type":"bullet","before":"ehlrkzlO","after":"kLYf6pif"},
  {"content":[{"insert":"Hashtag on twitter: #workingsmart,#productivityyrway, #CRM, #entrepenure"}],"id":"kLYf6pif","level":7,"type":"bullet","before":"T_Guz34Z","after":"Vi5XiHEP"},
  {"content":[{"insert":"Topics on Twitter: Transpose for users (teacher, project manager, Show us your stories when using transpose"}],"id":"Vi5XiHEP","level":7,"type":"bullet","before":"kLYf6pif","after":"DjH2o3Fr"},
  {"content":[{"insert":"The pseudo-partnership: create Kustome note - an Evernote add-on/app which create evernote templates: ricky"}],"id":"DjH2o3Fr","level":6,"type":"bullet","before":"Vi5XiHEP","after":"pq01YNXa"},
  {"content":[{"insert":"Create public community on Transpose: gie users the ability to publicize, share, and copy one another’s templates and organization solutions via Transpose."}],"id":"pq01YNXa","level":6,"type":"bullet","before":"DjH2o3Fr","after":"-6fpP0BE"},
  {"content":[{"insert":"Building blog "}],"id":"-6fpP0BE","level":6,"type":"bullet","before":"pq01YNXa","after":"kME7AZjM"},
  {"content":[{"insert":"Hacker New"}],"id":"kME7AZjM","level":4,"type":"bullet","before":"-6fpP0BE","after":"nds7F4NR"},
  {"content":[{"insert":"Get feedback in here:https://news.ycombinator.com/item?id=10310315"}],"id":"nds7F4NR","level":5,"type":"bullet","before":"kME7AZjM","after":"KCnNRnfw"},
  {"content":[{"insert":"Techcrunch"}],"id":"KCnNRnfw","level":4,"type":"bullet","before":"nds7F4NR","after":"B84h67l2"},
  {"content":[{"insert":"http://www.geekwire.com/2015/kustomnote-rebrands-as-transpose-raises-1-5m-for-holistic-information-management-platform/"}],"id":"B84h67l2","level":5,"type":"bullet","before":"KCnNRnfw","after":"b67CHMCk"},
  {"content":[{"insert":"https://www.crunchbase.com/organization/transpose"}],"id":"b67CHMCk","level":5,"type":"bullet","before":"B84h67l2","after":"RHrtuLNf"},
  {"content":[{"insert":"Betalist"}],"id":"RHrtuLNf","level":4,"type":"bullet","before":"b67CHMCk","after":"AOpM9CfE"},
  {"content":[{"insert":"Product hunt"}],"id":"AOpM9CfE","level":4,"type":"bullet","before":"RHrtuLNf","after":"hD1ZZsEw"},
  {"content":[{"insert":"The nextweb"}],"id":"hD1ZZsEw","level":4,"type":"bullet","before":"AOpM9CfE","after":"DgITL0oB"},
  {"content":[{"insert":"First Growth Review"}],"id":"DgITL0oB","level":4,"type":"bullet","before":"hD1ZZsEw","after":"qEETEbeI"},
  {"content":[{"insert":"Keywords to finding"}],"id":"qEETEbeI","level":3,"type":"bullet","before":"DgITL0oB","after":"sNevzj3Y"},
  {"content":[{"insert":"Transpose launch, "}],"id":"sNevzj3Y","level":4,"type":"bullet","before":"qEETEbeI","after":"Pm5x-En1"},
  {"content":[{"insert":"Android"}],"id":"Pm5x-En1","level":1,"type":"bullet","before":"sNevzj3Y","after":"BXZGqbFb"},
  {"content":[{"insert":"Note"}],"id":"BXZGqbFb","level":1,"type":"bullet","before":"Pm5x-En1","after":"pUEiI1Fc"},
  {"content":[{"insert":"People"}],"id":"pUEiI1Fc","level":2,"type":"bullet","before":"BXZGqbFb","after":"N3_kZ989"},
  {"content":[{"insert":"Finance"}],"id":"N3_kZ989","level":2,"type":"bullet","before":"pUEiI1Fc","after":"eWYlgkL_"},
  {"content":[{"insert":"Process"}],"id":"eWYlgkL_","level":2,"type":"bullet","before":"N3_kZ989","after":"e_r29NUl"},
  {"content":[{"insert":"Delivery"}],"id":"e_r29NUl","level":2,"type":"bullet","before":"eWYlgkL_","after":"vTnSrjE3"},
  {"content":[{"insert":"Marketing"}],"id":"vTnSrjE3","level":3,"type":"bullet","before":"e_r29NUl","after":"Oe4dE57n"},
  {"content":[{"insert":"Lead customer"}],"id":"Oe4dE57n","level":4,"type":"bullet","before":"vTnSrjE3","after":"4GQyzG_2"},
  {"content":[{"insert":"Interest"}],"id":"4GQyzG_2","level":4,"type":"bullet","before":"Oe4dE57n","after":"zCj_z5yf"},
  {"content":[{"insert":"5 minutes on site"}],"id":"zCj_z5yf","level":5,"type":"bullet","before":"4GQyzG_2","after":"aZzXBrx9"},
  {"content":[{"insert":"Tracking"}],"id":"aZzXBrx9","level":3,"type":"bullet","before":"zCj_z5yf","after":"HVkUgF7J"},
  {"content":[{"insert":"Metrics"}],"id":"HVkUgF7J","level":3,"type":"bullet","before":"aZzXBrx9","after":"FJc75Mvk"},
  {"content":[{"insert":"Note"}],"id":"FJc75Mvk","level":2,"type":"bullet","before":"HVkUgF7J","after":"3su5KNWN"},
  {"content":[{"insert":"$3000 / thang"}],"id":"3su5KNWN","level":3,"type":"bullet","before":"FJc75Mvk","after":"iIMtGhfV"},
  {"content":[{"insert":"50 dyno heroku"}],"id":"iIMtGhfV","level":3,"type":"bullet","before":"3su5KNWN","after":"vFSjyd_t"},
  {"content":[{"insert":"150"}],"id":"vFSjyd_t","level":3,"type":"bullet","before":"iIMtGhfV","after":null},
]
